### ISSUE TITLE
Реализовать продукт, основываясь на ранее спроектированных частях

### ISSUE THREAD

**Issue by maria35172** [amelchinkova80/kursovaya#8]
Было описано:
1. Видение проекта
2. Функциональная диаграмма
3. Архитектура проекта
Основываясь на выше указанных данных, необходимо реализовать MVP телеграм бота.

**Comment by amelchinkova80** [comment]
Реализовала MVP:
1. Модель БД и физическую модель также
2. Код для работы с БД
3. Код для работы с ТГ ботом
4. Добавила информацию в ПЗ
